---
- hosts: localhost
  connection: local
  remote_user: root
#  vars_files:
 #  - /root/playbook/mas.j2
  tasks:
   - name: Template
     template: src=/root/playbook/mas.j2 dest=/root/jinja
   - name: Create users
     shell: useradd -m -s /bin/bash $(cat /root/jinja)
