---
- hosts: 
  become: yes
  become_method: su
  remote_user: ec2-user
  tasks:
   - name: Add Global DNS
     lineinfile: path=/etc/resolv.conf insertafter=regex regex=^search line="nameserver 8.8.8.8"

